import {Metadata} from "next";
import Link from "next/link";

export const metadata: Metadata = {
	title: 'Blog | Next App',
	description: 'Generated by create next app',
}

async function getData() {
	const response = await fetch("https://jsonplaceholder.typicode.com/posts", {
		next: {
			// запрос будет происходить раз в минуту
			revalidate: 60,
		}
	})

	if (!response.ok) throw new Error("Unable fetch posts, !!!!")

	return response.json()
}

export default async function Blog() {
	const posts = await getData()
	return (
		<div>
			<h2>Blog</h2>
			<ul>
				{posts.map((post: any) => (
					<li key={post.id}>
						<Link href={`/blog/${post.id}`}>{post.title}</Link>
					</li>
				))}
			</ul>
		</div>
	)
}
