import './globals.css'
import { Inter } from 'next/font/google'
import {Metadata} from "next";
import React from "react";
import TheHeader from "@/components/TheHeader";
import TheFooter from "@/components/TheFooter";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <TheHeader/>
      <body className={inter.className}>{children}</body>
      <TheFooter/>
    </html>
  )
}
